import { GetStaticProps } from 'next'
import Head from 'next/head'
import Link from 'next/link'

import { POSTS_QUERY } from 'queries/posts.query'
import { client } from 'utils/apollo-client'
import { Posts } from 'types'

type Props = {
  posts: Posts
}

const Index = ({ posts }: Props): JSX.Element => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>
          <Link href="/">BEYOND</Link>
        </h1>
      </header>
      <main>
        {posts.map((post, i) => {
          return (
            <div key={i}>
              <Link href={`/posts/${post.slug}`}>
                <button>
                  <h3>{post.title}</h3>
                </button>
              </Link>
            </div>
          )
        })}
      </main>
      <footer></footer>
    </div>
  )
}

export default Index

export const getStaticProps: GetStaticProps = async () => {
  const { data } = await client.query({
    query: POSTS_QUERY,
  })
  return {
    props: {
      posts: data.posts,
    },
  }
}
