import { GetStaticProps } from 'next'
import Head from 'next/head'
import Link from 'next/link'

import { Posts } from '../../types'

type Props = {
    posts: Posts
}

const Index = ({ posts }: Props): JSX.Element => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <h1>
                    <Link href="/">BEYOND</Link>
                </h1>
            </header>
            <main>
                {posts.map((post, i) => {
                    return (
                        <div key={i}>
                            <Link href={`/posts/${post.id}`}>
                                <button>
                                    <p>No, {post.id}</p>
                                    <h3>{post.title}</h3>
                                </button>
                            </Link>
                        </div>
                    )
                })}
            </main>

            <footer></footer>
        </div>
    )
}

export default Index

export const getStaticProps: GetStaticProps = async () => {
    return {
        props: {
            posts: [
                {
                    id: 1,
                    title: 'post1',
                    content: 'post1 content',
                },
                {
                    id: 2,
                    title: 'post2',
                    content: 'post2 content',
                },
                {
                    id: 3,
                    title: 'post3',
                    content: 'post3 content',
                },
            ],
        },
    }
}
