import { POST_QUERY } from './post.query'
import {
  PAGE_INFO,
  POSTS_SLUG_QUERY,
  POST_CORE_FIELDS,
  SEO_CORE_FIELDS,
  COMMON_POSTS_FIELDS,
  POSTS_QUERY,
  FILTERD_POSTS_QUERY,
  FILTERD_POSTS_QUERY_WITH_TAGS,
} from './posts.query'

export {
  POST_QUERY,
  PAGE_INFO,
  POSTS_SLUG_QUERY,
  POST_CORE_FIELDS,
  SEO_CORE_FIELDS,
  COMMON_POSTS_FIELDS,
  POSTS_QUERY,
  FILTERD_POSTS_QUERY,
  FILTERD_POSTS_QUERY_WITH_TAGS,
}
